version: '3.9'

services:
  ta_producer:
    container_name: ta_producer
    build:
      context: ./producer
      dockerfile: Dockerfile
    restart: always
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=ta_kafka:9092
      - SERVER_PORT=8000
    networks:
      - takafkanetwork
      - taservicesnetwork

  taevaluator:
    container_name: taevaluator
    build:
      context: ./evaluator
      dockerfile: Dockerfile
    restart: always
    networks:
      - taservicesnetwork

  taevaluator1:
    container_name: taevaluator1
    build:
      context: ./evaluator
      dockerfile: Dockerfile
    restart: always
    networks:
      - taservicesnetwork

  ta_language_detector:
    container_name: ta_language_detector
    build:
      context: ./language-detector
      dockerfile: Dockerfile
    restart: always
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=ta_kafka:9092
      - SERVER_PORT=8000
      - EVALUATOR_HOST=http://taevaluator:5000
    networks:
      - takafkanetwork
      - taservicesnetwork

  ta_sentiment_detector:
    container_name: ta_sentiment_detector
    build:
      context: ./sentiment-detector
      dockerfile: Dockerfile
    restart: always
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=ta_kafka:9092
      - SERVER_PORT=8000
      - EVALUATOR_HOST=http://taevaluator1:5000
    networks:
      - takafkanetwork
      - taservicesnetwork

  ta_entity_detector:
    container_name: ta_entity_detector
    build:
      context: ./entity-detector
      dockerfile: Dockerfile
    restart: always
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=ta_kafka:9092
      - SERVER_PORT=8000
    networks:
      - takafkanetwork
      - taservicesnetwork

  ta_statistic_builder:
    container_name: ta_statistic_builder
    ports:
      - 8000:8000
    build:
      context: ./statistic-builder
      dockerfile: Dockerfile
    restart: always
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=ta_kafka:9092
      - SERVER_PORT=8000
    networks:
      - takafkanetwork
      - taservicesnetwork

networks:
  takafkanetwork:
    external:
      name: takafkanetwork

  taservicesnetwork:
    driver: bridge